stages:
  - prepare
  - test
  - build
  - package
  - release

include:
  - local: /.gitlab/ci/meta/meta.gitlab-ci.yml
  - local: /.gitlab/ci/prepare/prepare.gitlab-ci.yml
  - local: /.gitlab/ci/test/test.gitlab-ci.yml
  - local: /.gitlab/ci/build/build.gitlab-ci.yml
  - local: /.gitlab/ci/package/package.gitlab-ci.yml
  - local: /.gitlab/ci/release/release.gitlab-ci.yml
