include:
  - local: /.gitlab/ci/package/_app.gitlab-ci.yml

# package_stage is used as a sentinel for "Package" stage completion, so we can kick off jobs in later stages
# without waiting for the completion of the Package stage
package_stage:
  stage: package
  needs:
    - build_stage
  extends:
    - .at_stage
