default:
  retry:
    max: 2
    when:
      - runner_system_failure

.no_cache:
  cache: {}

.no_dependencies:
  dependencies: []

.no_cache_and_dependencies:
  extends:
    - .no_cache
    - .no_dependencies

# .at_stage is used as a sentinel at stage n for stage n-1 completion, so we can kick off builds in later stages
# without explicitly waiting for the completion of the n-1 stage
.at_stage:
  extends:
    - .no_cache_and_dependencies
  image: alpine:latest
  variables:
    GIT_STRATEGY: none
  script:
    - exit 0

##########################################
# region windows variables and base jobs #
##########################################

.windows1809_variables:
  variables:
    WINDOWS_VERSION: servercore1809

.windows1809:
  extends:
    - .windows1809_variables
  tags:
    - shared-windows
    - windows
    - windows-1809

.windows2004_variables:
  variables:
    WINDOWS_VERSION: servercore2004

.windows2004:
  extends:
    - .windows2004_variables
  tags:
    - windows
    - windows-2004

.windows20H2_variables:
  variables:
    WINDOWS_VERSION: servercore20H2

.windows20H2:
  extends:
    - .windows20H2_variables
  tags:
    - windows
    - windows-20h2
# endregion
