#####################
# region conditions #
#####################

.if-default-branch: &if-default-branch
  if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

.if-stable-release: &if-stable-release
  if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/'

.if-docs-branch: &if-docs-branch
  if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /(^docs[\/-].*|.*-docs$)/

.if-merge-request-pipeline: &if-merge-request-pipeline
  if: $CI_PIPELINE_SOURCE == "merge_request_event"

.if-windows-is-target: &if-windows-is-target
  if: "$_TARGETS =~ /{windows}/"

.if-linux-is-target: &if-linux-is-target
  if: "$_TARGETS =~ /{linux}/"

.if-darwin-is-target: &if-darwin-is-target
  if: "$_TARGETS =~ /{darwin}/"

# endregion

###############################
# region default branch rules #
###############################

.rules/default-branch-only:
  rules:
    - <<: *if-default-branch

.rules/default-branch-only:always:
  rules:
    - <<: *if-default-branch
      when: always

# endregion

##############################
# region build rules         #
##############################

.rules/build-windows:
  rules:
    - <<: *if-windows-is-target

.rules/build-linux:
  rules:
    - <<: *if-linux-is-target

.rules/build-darwin:
  rules:
    - <<: *if-darwin-is-target

# endregion

##############################
# region testing rules       #
##############################

.rules/test-windows:
  rules:
    - <<: *if-windows-is-target

.rules/test-linux:
  rules:
    - <<: *if-linux-is-target

.rules/test-darwin:
  rules:
    - <<: *if-darwin-is-target

# endregion

##############################
# region merge Request Rules #
##############################

.rules/merge_request_pipelines:
  rules: &merge-request-pipelines-rules
    - <<: *if-merge-request-pipeline
    - <<: *if-default-branch
    - <<: *if-stable-release

.rules/merge_request_pipelines:no_docs:
  rules:
    - *merge-request-pipelines-rules
    - <<: *if-docs-branch
      when: never

.rules/merge_request_pipelines:no_docs:always:
  rules:
    - <<: *if-docs-branch
      when: never
    - <<: *if-merge-request-pipeline
      when: always
    - <<: *if-merge-request-pipeline
      when: always
    - <<: *if-default-branch
      when: always
    - <<: *if-stable-release
      when: always

# endregion

########################
# region release rules #
########################

.rules/release:all:
  rules:
    - <<: *if-default-branch
    - <<: *if-stable-release

# endregion

#####################
# region docs rules #
#####################

.rules/docs:skip:
  rules:
    - <<: *if-docs-branch
      when: never
    - when: on_success
# endregion
